version: '3'

services:
    bot:
        build: .
        restart: always
        volumes:
            - .:/app
        ports:
            - 80:80
        image: app:bot
        container_name: bot
        command: python main.py

